- rudimentary name validation

diff --git a/bin/launch-container b/bin/launch-container
--- a/bin/launch-container
+++ b/bin/launch-container
@@ -1,9 +1,16 @@
 #! /bin/bash
 
+NAME=$1
+if [ -z $NAME ]
+then
+	echo "container name is required"
+	exit 1
+fi
+
 CURRENT_DIR=$(pwd)
 INSTALL_DIR=/srv/aims
 docker start $(docker create \
-	--name $1 \
+	--name $NAME \
 	--link elk-server:logstash.example.org \
 	--link db \
 	-v $CURRENT_DIR/../data/config:$INSTALL_DIR/application/config \
